spring:
  kafka:
    security:
      protocol: SASL_SSL
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      ssl:
        endpoint:
          identification:
            algorithm: ""
      sasl:
        mechanism: "SCRAM-SHA-256"
        jaas:
          config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"avnadmin\" password=\"T8MKzBtK5oruwua2\";"
    bootstrap-servers:
      - "kafka-3f01822f-cashflow35-d0e8.aivencloud.com:13129"
    ssl:
      trust-store-type: "jks"
      trust-store-location: client.truststore.jks
      trust-store-password: "123456"
      key-store-type: "PKCS12"
      key-store-password: "123456"
      key-store-location: client.keystore.p12
      key-password: "123456"
